x <- c(1:5)  
mean(x)     
var(x)   
sd(x)   
fivenum(1:100)
summary(1:100)
summary(iris)             
x <- factor(c("A","B","C","D","D","C","A","A","A")) 
table(x)
which.max(table(x))
which.min(table(x))